language: java
before_script:
  echo $TRAVIS_BRANCH
  echo $TRAVIS_TAG
  echo $TRAVIS_PULL_REQUEST
jdk:
  - oraclejdk8
cache:
  directories:
    - /home/travis/.gradle/wrapper/dists/gradle-2.3-all/w01pvxy5gty3tegjrai84pm3
after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then

    echo "This will deploy!"

  else

    echo "This will not deploy!"

  fi