sudo: false
language: java
before_install:
  echo $TRAVIS_BRANCH $TRAVIS_TAG $TRAVIS_PULL_REQUEST
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/
after_success:
  if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then

    ./gradlew uploadArchives

    ./gradlew nexusStagingRelease

  fi
